
UNICODE=1
UNDEF_NDEBUG=1
INSTALL_MULTIVERSION=1
FLAVOUR="dbg"
EP_ADD_OPTS=1
EP_FULL_VER=0
WX_CONFIG="wx-config --version=2.8 --toolkit=gtk2 --static=no --unicode --debug"
WXPORT="gtk2"
MONOLITHIC=0
FINAL=0
HYBRID=1
