#!/bin/bash

if [ "$1" != "" ]; then
    WXPORT="WXPORT=$1"
    WX_CONFIG="WX_CONFIG=../bld/$1/wx-config"
else
    WX_CONFIG="WX_CONFIG=../bld/osx_carbon/wx-config"
fi

python2.6 -u ./setup.py --debug \
    PREP_ONLY=1 \
    SWIG="/opt/swig/bin/swig-1.3.29" \
    USE_SWIG=1 \
    UNICODE=1 \
    BUILD_BASE=build.tmp \
    $WXPORT \
    $WX_CONFIG


